### PR TITLE
Features/SSOR-55-view_transaction:Back End

### PR DESCRIPTION
**Pull request by BermondSmoothStack**
Current endpoints implemented:

A list of transactions
`api/accounts/{account_id}/{account_type}/transactions`
Returns a JSON/XML representation of a user's account associated with its account ID and account type.
Returns a 400 Bad Request if account type is malformed, specifically if it is not `saving` or `checking`.

A transaction
`api/accounts/{account_id}/{account_type}/transactions/1`
Returns a JSON/XML representation of a user's account associated with its account ID and account type and the ID of that transaction.
Returns a 400 Bad Request if account type is malformed, specifically if it is not `saving` or `checking`.

A list of filtered transactions
`api/accounts/{account_id}/{account_type}/transactions?keyword=`
Returns a JSON/XML representation of a user's account associated with its account ID and account type filtered through a keyword.
Returns a 400 Bad Request if account type is malformed, specifically if it is not `saving` or `checking`.

### CODE REVIEW

**Review by LeftRuleMatters — CHANGES_REQUESTED** [review]
May want to ignore your `.idea` folder and make sure your `targets` folder is ignored because it looks like they aren't

**Comment by BermondSmoothStack** [comment]
Done!

**Comment by BermondSmoothStack** [comment]
@LeftRuleMatters Reopened PR.

**Review by LeftRuleMatters — APPROVED** [review]

**Comment by BermondSmoothStack** [comment]
added signed commit. i forgot to sign them lol

**Review by LeftRuleMatters — APPROVED** [review]

**Review by LeftRuleMatters — APPROVED** [review]

**Pull request merged**
